name: fish_freshness_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  tflite_flutter: ^0.11.0
  image: ^4.0.17
  desktop_drop: ^0.4.3
  file_picker: ^8.0.0
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/fish_model.tflite